personal_portfolio_project/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('Tunde/', views.Tunde, name='Tunde'),
]

personal_portfolio_project/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

personal_portfolio_project/blog/models.py
from django.db import models
from django.utils.timezone import now

class Blog(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    dateStamp =  models.DateTimeField(default=now)

    def __str__(self):
        return self.title

personal_portfolio_project/portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

personal_portfolio_project/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/all_blogs.html', {'blogs' : blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

def Tunde(request):
    return HttpResponse('THIS IS IT')

personal_portfolio_project/portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects' : projects})

personal_portfolio_project/blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html'%}
{% block content %}
  <h2>Tunde has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

  {% for blog in blogs %}
    <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
    <p>{{ blog.description|striptags|safe|truncatechars:100 }}</p>
    <p><b>{{ blog.dateStamp|date:'l jS F Y' }}</b></p>
  {% endfor %}
{% endblock %}

personal_portfolio_project/blog/templates/blog/detail.html
{% extends 'portfolio/base.html'%}
{% block content %}
  <h1>{{ blog.title }}</h1>
  <p>{{ blog.description|safe }}</p>
{% endblock %}

personal_portfolio_project/portfolio/templates/portfolio/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "/portfolio/custom.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&display=swap">
    <link rel="icon" type="image/png" href="{% static "/portfolio/Logo.png" %}">

    <title>Home Page</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

personal_portfolio_project/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html'%}
{% block content %}
      <h1>This is my real home :-)</h1>

      {% load static %}

      <a href="{% url 'blog:all_blogs' %}">Link</a>
      <br>
      <img src="{% static 'portfolio/Tunde_Ajao.jpg' %}">
      <a href="{% static 'portfolio/AgainstGrain.pdf' %}">Against Grain</a>
      {% for project in projects %}
        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>
        <img src="{{ project.image }}" alt="">

        {% if project.url %}
        <br><a href="{{ project.url }}">Link</a>
        {% endif %}
      {% endfor %}
{% endblock %}